accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from accounts.views import CreateProfilePhoto

app_name = 'accounts'

urlpatterns = [
    url(r"proPic/",CreateProfilePhoto.as_view(),name = 'proPic'),
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

emo_music/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
     url(r'^admin/', admin.site.urls),
     url(r"^$", views.HomePage.as_view(), name="home"),
     url(r"^test/$", views.TestPage.as_view(), name="test"),
     url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
     url(r"^emotion/$", views.EmotionTemp, name="emotion"),
     url(r"^accounts/", include("accounts.urls", namespace="accounts")),
     url(r"^accounts/", include("django.contrib.auth.urls")),
     url(r"^user/",views.save_image,name="user"),
     url(r'^musicapp/',include('musicapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html >
<head>
  <meta charset="UTF-8">
  <title>Emosic</title>
	<link rel="icon" type="image/vnd.microsoft.icon" href="{% static 'images/music_icon.ico' %}">
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
</head>

<body>

  <div id="bg"></div>

  <div class="topnav">
  	<a class="active" href="{% url 'home' %}"><i class="fa fa-music" aria-hidden="true" style="font-size:40px;color:#fff;"></i></a>

    {% if user.is_authenticated %}

    <a href="{% url 'accounts:logout' %}" >LogOut</a>
    {% block userProfileBlock %}

    {% endblock %}
    {% else %}
    {% endif %}
    <a href="#about">About Emosic</a>

  </div>



 </br>

  {% block content %}

  {% endblock %}

<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
</body>
</html>

templates/emotion.html
{% extends "base.html" %}
{% block userProfileBlock %}
  <span style="font-size:16px;cursor:pointer;position:relative;color:#fff;text-shadow: 2px 2px 4px #000000;margin-top:15px;float:right;" onclick="openNav()"><i class="fa fa-user"  style="color:#fff;text-shadow: 2px 2px 4px #000000;" aria-hidden="true"></i> User Profile</span>
{% endblock %}

{% block content %}

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <h2 style="text-align:center;color:#D9E2D5;">User Profile</h2>
  <!--profile box-->
  <div class="card">
      {% if flag %}
      <img src="{{allprophoto.profilephoto.url}}" alt="" style="height:150px;width:150px;border-radius:50%;">
      {% else %}
      <a href="{% url 'accounts:proPic' %}"><img src="/static/images/uploadphoto.png" alt="" style="height:150px;width:150px;border-radius:50%;"></a>
      {% endif %}
      <h1 style="color:#EAEFE8;">{{user.username}}</h1>
      <p class="title">EMAIL id</p>
      <div style="margin: 24px 0;">
      <a href="#"><i class="fa fa-facebook"></i></a>
  </div>
</div>
 <!--end profile box-->
</div>

<!--side nav ends---->

<div class="container-fluid">
<div class="row">
  <div class="col-sm-6">
    {% if emotionFoundtag %}
     <center><h2 style="display:inline;color:#E3EEDF;text-shadow: 2px 2px 4px #000000;">Hey!! Your are :</h2> 
   <img src="/static/emosis/{{emotionFoundtag}}.png" alt="" style="position:relative;display:inline;height:60px;width:60px;"></center>
   {% endif %}
 </br>
 <h3 style="color:#E3EEDF;text-shadow: 2px 2px 4px #000000;">Here are the TOP SONGS for you. Enjoy!!</h3>
 <strong><hr style="color:#787C77;"></strong>
 </br>

  {% if songlist %}
  {% for ob in songlist %}

  {% if ob.emotionAttached == emotionFoundtag %}

    <audio controls style="position:relative;display:inline;margin-right:5px;border-radius:3px;background-color:#737970;">
         <source src="{{ ob.audio_file.url }}" type="audio/mpeg">
    </audio>
    <h4 style="position:relative;color:#E3EEDF;text-shadow: 2px 2px 4px #000000;display:inline;">{{ob.name}}</h4>
  <hr style="color:#A4A9A3;">
  {% endif %}
  {% endfor %}
</div><!--end col1-->

<!--col2-->
<div class="col-sm-6" style="padding-top:61px;">
</br>
  <center><h3 style="position:relative;color:#E3EEDF;text-shadow: 2px 2px 4px #000000;">Some popular social platforms</h3></center>
  <hr style="color:#A4A9A3;">
  <div class="container-fluid">
    <center><a style="position:relative;" class="social1" href="https://www.youtube.com/results?search_query={{emotionFoundtag}}+songs"><button type="button" name="button"><img src="/static/images/youtube1_logo.png" style="width:100px;height:100px;"></button></a></center>
    <center><center><h2 style="position:relative;color:#E3EEDF;text-shadow: 2px 2px 4px #000000;">-OR-</h2></center>
    <center><a style="position:relative;" class="social1" href="https://gaana.com/search/{{emotionFoundtag}}%20songs"><button type="button" name="button"><img src="/static/images/ganna.com_logo.png" style="width:100px;height:100px;border-radius:5px;"></button></a></center>
  {% endif %}
</div>
</div><!--end col2-->
</div>
  <script>
  function openNav() {
      document.getElementById("mySidenav").style.width = "100%";
  }

  function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
  }
  </script>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}

{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block userProfileBlock %}
  <span style="font-size:16px;cursor:pointer;position:relative;color:#fff;text-shadow: 2px 2px 4px #000000;margin-top:15px;float:right;" onclick="openNav()"><i class="fa fa-user"  style="color:#fff;text-shadow: 2px 2px 4px #000000;" aria-hidden="true"></i> User Profile</span>
{% endblock %}

{% block content %}
<style>

/********************************************************************************/
</style>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <h2 style="text-align:center;color:#D9E2D5;">User Profile</h2>
  <!--profile box-->
  <div class="card">
    {% if flag %}
     <img src="{{allprophoto.profilephoto.url}}" alt="" style="height:150px;width:150px;border-radius:50%;">
    {% else %}
    <a href="{% url 'accounts:proPic' %}"><img src="/static/images/uploadphoto.png" alt="" style="height:150px;width:150px;border-radius:50%;"></a>
    {% endif %}
      <h1 style="color:#EAEFE8;">{{user.username}}</h1>
      <p class="title">{{user.email}}</p>
      <div style="margin: 24px 0;">
      <a href="https://mail.google.com" style="margin-left:-15px;"><i class="fa fa-google-plus-official" aria-hidden="true"></i></a>
  </div>

  </div>
 <!--end profile box-->
</div>


<!--side nav ends---->

<div class="container-fluid">
<div class="row">
<!--col1-->
<div class="col-sm-12" style="padding-left:70px;padding-top:30px;">
<center><div id="camera1">
  <table><tr><td valign=top>


		<!-- First, include the JPEGCam JavaScript Library -->
		<script type="text/javascript" src="/static/jpegcam/webcam.js"></script>

    <br/><form>
		<!-- Configure a few settings -->
		<script language="JavaScript">
			webcam.set_api_url( '/user/' );
			webcam.set_quality( 90 ); // JPEG quality (1 - 100)
			webcam.set_shutter_sound( true ); // play shutter click sound
		</script>

		<!-- Next, write the movie to the page at 320x240 -->
		<script language="JavaScript">
			document.write( webcam.get_html(500, 400) );
		</script>

		<!-- Some buttons for controlling things -->

			{# <input type=button value="Configure..." onClick="webcam.configure()">#}
    <br/>
			<center><input type=button value="TAKE SNAPSHOT" onClick="take_snapshot()" style="margin-top:20px;"></center>
		</form>

		<!-- Code to handle the server response (see test.php) -->
		<script language="JavaScript">
			webcam.set_hook( 'onComplete', 'my_completion_handler' );

			function take_snapshot() {
				// take snapshot and upload to server
				//document.getElementById('upload_results').innerHTML = '<h1>Uploading...</h1>';
          document.getElementById('upload_results').innerHTML = '<div class="loader"></div>';
        webcam.snap();
			}

			function my_completion_handler(msg) {
				if (msg.match(/(http\:\/\/\S+)/)) {
					var image_url = RegExp.$1;
					// show JPEG image in page
	     window.location.href = "http://127.0.0.1:8000/emotion/";
					document.getElementById('upload_results').innerHTML =
						'<div class="loader"></div>';
					// reset camera for another shot
					webcam.reset();
				}
				else alert("Python Error: " + msg);
			}
		</script>

		</td><td width=50>&nbsp;</td><td valign=top>
			<div id="upload_results" style="background-color:#eee;"></div>
		</td></tr></table>

 </div></center>
</div><!--end of col1-->


</div><!--end of row--->
</div><!--end of container fluid-->

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "100%";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>
	{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}